# Generated by Django 3.1.6 on 2021-06-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nStudentId', models.CharField(default='', max_length=12)),
                ('nPrecincts', models.CharField(default='', max_length=5)),
                ('nStatus', models.TextField(default='')),
                ('nFullName', models.TextField(default='')),
                ('nAddress', models.TextField(default='')),
                ('nGenders', models.TextField(default='')),
                ('nDBirths', models.DateTimeField(default='')),
                ('nAges', models.CharField(default='', max_length=2)),
                ('nMoNames', models.TextField(default='')),
                ('nOccupation1', models.TextField(default='')),
                ('nFaNames', models.TextField(default='')),
                ('nOccupation2', models.TextField(default='')),
                ('nAIncome', models.CharField(default='', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
