# Generated by Django 3.1.6 on 2021-05-13 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carolslist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Applicant',
        ),
    ]
