# Generated by Django 3.1.6 on 2021-06-01 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carolslist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NMSchool', models.TextField(default='')),
                ('SAddress', models.TextField(default='')),
                ('YSection', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='nAges',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='nPrecincts',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='nStatus',
        ),
        migrations.AddField(
            model_name='school',
            name='applicant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='carolslist.applicant'),
        ),
    ]
