# Generated by Django 3.1.6 on 2021-06-02 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carolslist', '0002_auto_20210601_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='applicant',
            new_name='Napplicant',
        ),
    ]
