# Generated by Django 3.1.6 on 2021-06-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carolslist', '0003_auto_20210602_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='nDBirths',
        ),
    ]
