# Generated by Django 3.1.6 on 2021-08-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carolslist', '0007_auto_20210809_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='nAIncome',
            field=models.IntegerField(default='0'),
        ),
    ]
