# Generated by Django 3.1.6 on 2021-08-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carolslist', '0008_auto_20210818_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='nStudentId',
            field=models.ImageField(default='', max_length=12, upload_to=''),
        ),
    ]
