# Generated by Django 3.1.6 on 2021-08-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carolslist', '0009_auto_20210821_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='n1StudentId',
            field=models.TextField(default=''),
        ),
    ]
