# Generated by Django 3.1.6 on 2021-08-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carolslist', '0010_applicant_n1studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='NMSchool',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='applicant',
            name='SAddress',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='applicant',
            name='YSection',
            field=models.TextField(default=''),
        ),
    ]
