# Generated by Django 3.1.6 on 2021-08-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carolslist', '0011_auto_20210821_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='n1GPA',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='nGPA',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='nStudentId',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
