# Generated by Django 3.1.6 on 2021-08-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carolslist', '0014_auto_20210821_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='n1GPA',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
