# Generated by Django 3.1.6 on 2021-08-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carolslist', '0016_auto_20210821_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminu', models.TextField(default='')),
                ('adminp', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NMSchool', models.TextField(default='')),
                ('slevel', models.TextField(default='')),
                ('nStudentId', models.TextField(default='')),
                ('nGPA', models.IntegerField(default='0')),
                ('sstatus', models.TextField(default='')),
                ('sid', models.ImageField(default='', upload_to='')),
                ('sgwa', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='grades',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='school',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='typesofscholarship',
            name='applicant',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='NMSchool',
            new_name='aemailAddress',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='SAddress',
            new_name='agname',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='YSection',
            new_name='apassword',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='n1StudentId',
            new_name='asoi',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='nFaNames',
            new_name='ausername',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='n1GPA',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='nGPA',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='nMoNames',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='nOccupation1',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='nOccupation2',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='nStudentId',
        ),
        migrations.AddField(
            model_name='applicant',
            name='aage',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='acontumber',
            field=models.IntegerField(default='0'),
        ),
        migrations.DeleteModel(
            name='Credentials',
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='TypesOfScholarship',
        ),
    ]
