# Generated by Django 3.1.6 on 2021-08-24 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carolslist', '0017_auto_20210823_0858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scholarship',
            new_name='School',
        ),
    ]
