# Generated by Django 3.1.6 on 2021-08-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carolslist', '0018_auto_20210824_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='applicant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='carolslist.applicant'),
        ),
    ]
