# Generated by Django 3.1.6 on 2021-08-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carolslist', '0019_school_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='sstatus',
        ),
        migrations.AddField(
            model_name='applicant',
            name='sstatus',
            field=models.TextField(default=''),
        ),
    ]
